version: '3'

volumes:
  dailyer_postgres_data: {}
  dailyer_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: dailyer_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: dailyer_postgres
    volumes:
      - dailyer_postgres_data:/var/lib/postgresql/data
      - dailyer_postgres_data_backups:/backups
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - 5080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=Passw0rd!

  redis:
    image: redis:3.2